version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: qwer
      MYSQL_DATABASE: review_service
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  spring-app:
    build: .
    container_name: spring-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/review_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: qwer
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_SQL_INIT_DATA_LOCATIONS: classpath:data.sql
      SPRING_SQL_INIT_MODE: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
    driver: bridge
