spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/review_service
    username: root
    password: qwer

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  sql:
    init:
      data-locations: classpath:data.sql
      mode: always
